// <auto-generated />
using System;
using LibraryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Tabitha Orn",
                            AverageRating = 0.0,
                            Category = "Kids",
                            Description = "Voluptate velit quos temporibus qui saepe ullam quas. Qui expedita perferendis aut reiciendis similique atque est minus impedit.",
                            ISBN = "1820921796795",
                            PageCount = 770,
                            PublicationDate = new DateTime(2024, 4, 2, 13, 47, 39, 653, DateTimeKind.Local).AddTicks(9202),
                            Publisher = "Rau Group",
                            Title = "Eligendi magni eaque."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Betty Johnson",
                            AverageRating = 0.0,
                            Category = "Electronics",
                            Description = "At et enim. Sequi saepe adipisci omnis vitae.",
                            ISBN = "1116983171909",
                            PageCount = 552,
                            PublicationDate = new DateTime(2011, 9, 22, 17, 34, 19, 970, DateTimeKind.Local).AddTicks(8801),
                            Publisher = "Rutherford and Sons",
                            Title = "Delectus dolores natus."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Lionel Mills",
                            AverageRating = 0.0,
                            Category = "Music",
                            Description = "Minima voluptatibus aut et exercitationem excepturi. Tempora placeat iste. Eos deleniti rerum occaecati dolores ut sapiente animi adipisci. Et accusantium dicta sint.",
                            ISBN = "7127883603890",
                            PageCount = 910,
                            PublicationDate = new DateTime(2018, 8, 29, 17, 6, 9, 110, DateTimeKind.Local).AddTicks(5396),
                            Publisher = "Ferry, Davis and Maggio",
                            Title = "Molestiae ullam eligendi."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Regina Raynor",
                            AverageRating = 0.0,
                            Category = "Games",
                            Description = "Ex nostrum eveniet dolor cumque velit repellat. Autem cumque perspiciatis eaque modi consequatur. Ea dicta possimus sit sequi vel ut deleniti eum. Mollitia a ut. Laudantium aliquid earum sed et reiciendis numquam exercitationem hic et.",
                            ISBN = "8331536789506",
                            PageCount = 926,
                            PublicationDate = new DateTime(2020, 11, 8, 21, 25, 30, 574, DateTimeKind.Local).AddTicks(4152),
                            Publisher = "Prosacco, Lang and Murray",
                            Title = "Sequi sed et."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Rachael Adams",
                            AverageRating = 0.0,
                            Category = "Shoes",
                            Description = "Recusandae rem reprehenderit itaque porro. Culpa velit et magnam sequi vel reprehenderit consectetur. Voluptatem ut velit repellat ducimus.",
                            ISBN = "4246945053336",
                            PageCount = 544,
                            PublicationDate = new DateTime(2022, 6, 18, 7, 2, 7, 594, DateTimeKind.Local).AddTicks(4289),
                            Publisher = "Kuhn, MacGyver and Bernhard",
                            Title = "Quia tempora eligendi."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Lora Mraz",
                            AverageRating = 0.0,
                            Category = "Garden",
                            Description = "Odio eum quia hic nisi. Amet eveniet amet facere laudantium soluta est.",
                            ISBN = "5320625797662",
                            PageCount = 672,
                            PublicationDate = new DateTime(2022, 10, 15, 20, 54, 16, 22, DateTimeKind.Local).AddTicks(6538),
                            Publisher = "Russel Group",
                            Title = "Omnis voluptatum in."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Eduardo Turcotte",
                            AverageRating = 0.0,
                            Category = "Electronics",
                            Description = "A rem doloribus quibusdam in. Error quia sit dolorem quam et. Assumenda omnis ut qui. Eos occaecati suscipit ad expedita quod commodi. Sit rerum earum.",
                            ISBN = "1561194364020",
                            PageCount = 666,
                            PublicationDate = new DateTime(2004, 12, 13, 13, 1, 11, 285, DateTimeKind.Local).AddTicks(3876),
                            Publisher = "Jacobson LLC",
                            Title = "Sunt optio molestiae."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Diane Yundt",
                            AverageRating = 0.0,
                            Category = "Electronics",
                            Description = "Et iste velit similique in. Dignissimos unde voluptas pariatur omnis et. Deserunt eveniet sed. Nostrum rem earum minus dolorum sed eligendi.",
                            ISBN = "4007723246421",
                            PageCount = 588,
                            PublicationDate = new DateTime(2023, 7, 16, 18, 32, 12, 848, DateTimeKind.Local).AddTicks(875),
                            Publisher = "Beatty, Morissette and Zemlak",
                            Title = "Eum inventore voluptates."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Dwight Heaney",
                            AverageRating = 0.0,
                            Category = "Beauty",
                            Description = "Dolore laborum numquam molestias. Nesciunt et aut unde sint optio animi quibusdam ut rerum.",
                            ISBN = "7739133736830",
                            PageCount = 463,
                            PublicationDate = new DateTime(2007, 6, 16, 3, 50, 18, 44, DateTimeKind.Local).AddTicks(8329),
                            Publisher = "Friesen - Kiehn",
                            Title = "Provident repudiandae id."
                        },
                        new
                        {
                            Id = 10,
                            Author = "Vera Hettinger",
                            AverageRating = 0.0,
                            Category = "Outdoors",
                            Description = "Ab porro dolor nulla qui deleniti. Aut nihil non officia impedit suscipit inventore quia. Aut est esse exercitationem doloremque molestiae.",
                            ISBN = "0188733749400",
                            PageCount = 710,
                            PublicationDate = new DateTime(2022, 4, 15, 10, 28, 40, 353, DateTimeKind.Local).AddTicks(9638),
                            Publisher = "Stokes, Carter and Casper",
                            Title = "Aut quidem ipsam."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Elijah Schaden",
                            AverageRating = 0.0,
                            Category = "Electronics",
                            Description = "Ea repudiandae explicabo. Sit ut qui minus itaque repellendus ut nulla non nobis. Voluptatibus perferendis provident amet voluptatem. Eos id omnis enim et. Ea a ipsum aspernatur aut.",
                            ISBN = "1209282832968",
                            PageCount = 573,
                            PublicationDate = new DateTime(2014, 5, 30, 14, 15, 38, 434, DateTimeKind.Local).AddTicks(2851),
                            Publisher = "Frami, Rice and Bernier",
                            Title = "Ex autem quisquam."
                        },
                        new
                        {
                            Id = 12,
                            Author = "Andrea Ward",
                            AverageRating = 0.0,
                            Category = "Grocery",
                            Description = "Ut itaque sit non nihil et enim sit laborum. Velit exercitationem dolor rem est veniam placeat ut tenetur dolor. Debitis quod nostrum aut est. Tenetur et laborum quisquam porro recusandae repudiandae. Quia aut praesentium rerum ipsa.",
                            ISBN = "2416290053813",
                            PageCount = 196,
                            PublicationDate = new DateTime(2007, 12, 16, 18, 42, 7, 300, DateTimeKind.Local).AddTicks(7977),
                            Publisher = "Dare Inc",
                            Title = "Et repudiandae consequuntur."
                        },
                        new
                        {
                            Id = 13,
                            Author = "Melissa Torphy",
                            AverageRating = 0.0,
                            Category = "Tools",
                            Description = "Quidem perspiciatis facilis mollitia veniam accusamus natus doloremque. Aut modi saepe. Commodi cupiditate cum molestiae numquam ut quis.",
                            ISBN = "9902894969481",
                            PageCount = 451,
                            PublicationDate = new DateTime(2019, 4, 5, 18, 2, 8, 855, DateTimeKind.Local).AddTicks(2793),
                            Publisher = "Cummerata, Schowalter and Lebsack",
                            Title = "Et rerum non."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Paulette Cole",
                            AverageRating = 0.0,
                            Category = "Shoes",
                            Description = "Illo voluptate impedit est. Totam adipisci nemo ipsum soluta. Id ab provident nam rem. Rem ad blanditiis nihil enim sunt labore quidem quae quia.",
                            ISBN = "7637362041131",
                            PageCount = 883,
                            PublicationDate = new DateTime(2006, 11, 4, 20, 42, 59, 232, DateTimeKind.Local).AddTicks(2589),
                            Publisher = "Brekke, Olson and Hahn",
                            Title = "Hic ea dolorem."
                        },
                        new
                        {
                            Id = 15,
                            Author = "Laverne Beahan",
                            AverageRating = 0.0,
                            Category = "Computers",
                            Description = "Eum dolorum et dolor est. Ducimus a sint ipsum dolores excepturi iusto. Quaerat reprehenderit tenetur aut. Nisi veritatis eum sit cupiditate exercitationem quia.",
                            ISBN = "9797949899604",
                            PageCount = 337,
                            PublicationDate = new DateTime(2021, 12, 19, 18, 26, 46, 321, DateTimeKind.Local).AddTicks(7258),
                            Publisher = "Macejkovic, Leannon and Dach",
                            Title = "Perspiciatis cupiditate quidem."
                        },
                        new
                        {
                            Id = 16,
                            Author = "Emma Bernhard",
                            AverageRating = 0.0,
                            Category = "Automotive",
                            Description = "Accusamus sunt ex possimus. Ut delectus fugiat nam vel quis architecto aperiam sed. Nesciunt veritatis non vero harum quis laudantium veniam ut ad.",
                            ISBN = "4183492613036",
                            PageCount = 943,
                            PublicationDate = new DateTime(2010, 2, 26, 3, 26, 41, 94, DateTimeKind.Local).AddTicks(8889),
                            Publisher = "Kuhlman and Sons",
                            Title = "Excepturi et ullam."
                        },
                        new
                        {
                            Id = 17,
                            Author = "Elias Cassin",
                            AverageRating = 0.0,
                            Category = "Industrial",
                            Description = "Excepturi enim in quas ea. Et odit cupiditate quod iure laboriosam. Et quaerat dolorum soluta. Molestiae odio quia est exercitationem ratione minus maxime sint eveniet.",
                            ISBN = "7582312106821",
                            PageCount = 885,
                            PublicationDate = new DateTime(2017, 11, 6, 17, 41, 33, 747, DateTimeKind.Local).AddTicks(5461),
                            Publisher = "Satterfield - Zieme",
                            Title = "Et aut rerum."
                        },
                        new
                        {
                            Id = 18,
                            Author = "Stuart Koss",
                            AverageRating = 0.0,
                            Category = "Outdoors",
                            Description = "Molestias odit id quia quasi. Voluptatem corporis molestias veritatis blanditiis qui quisquam minima et. Ea unde dolorem voluptas eum corporis maxime porro. Suscipit et est vel nostrum modi repellendus.",
                            ISBN = "4331245932952",
                            PageCount = 635,
                            PublicationDate = new DateTime(2006, 1, 2, 21, 26, 15, 168, DateTimeKind.Local).AddTicks(59),
                            Publisher = "Blanda, Swaniawski and Hand",
                            Title = "Tempore quisquam enim."
                        },
                        new
                        {
                            Id = 19,
                            Author = "Ignacio Kuhic",
                            AverageRating = 0.0,
                            Category = "Kids",
                            Description = "Neque vel aperiam et culpa. Sed magnam et ratione.",
                            ISBN = "6280350342171",
                            PageCount = 189,
                            PublicationDate = new DateTime(2007, 8, 28, 3, 8, 9, 913, DateTimeKind.Local).AddTicks(9281),
                            Publisher = "Glover, Gaylord and Leuschke",
                            Title = "Recusandae cum hic."
                        },
                        new
                        {
                            Id = 20,
                            Author = "Elmer Streich",
                            AverageRating = 0.0,
                            Category = "Clothing",
                            Description = "Magni necessitatibus magni recusandae. Possimus ut autem corrupti eum. Rerum voluptatem explicabo debitis nihil. Deleniti quisquam in qui beatae inventore atque quae.",
                            ISBN = "9921113050960",
                            PageCount = 439,
                            PublicationDate = new DateTime(2007, 12, 15, 14, 58, 19, 245, DateTimeKind.Local).AddTicks(5075),
                            Publisher = "Keebler LLC",
                            Title = "Assumenda deleniti voluptatem."
                        });
                });

            modelBuilder.Entity("LibraryApp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LibraryApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLibrarian")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4ac2132a-f25e-46b8-a4b1-fc4e0d01228b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0cc29c71-b8b5-4ac0-b893-fc27bb9d147a",
                            Email = "Richard_Stanton@yahoo.com",
                            EmailConfirmed = false,
                            IsLibrarian = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONRAD_MCCULLOUGH79@HOTMAIL.COM",
                            NormalizedUserName = "LONNIE57",
                            PasswordHash = "AQAAAAIAAYagAAAAEP2i2HtHIY2SdHerb2nT4CaDDbQ40xWyptp8UozCTc9ili/GrhUM/5zINOwJsB1+0g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8eee2d37-8f21-464f-8464-4acdab06dc7a",
                            TwoFactorEnabled = false,
                            UserName = "Jade_Moore46"
                        },
                        new
                        {
                            Id = "29ff7b35-167f-450a-9fa3-315d0c666724",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4781e553-a373-41d4-ac17-f3464b1a9a47",
                            Email = "Adela.Legros@gmail.com",
                            EmailConfirmed = false,
                            IsLibrarian = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "XANDER_ROHAN78@HOTMAIL.COM",
                            NormalizedUserName = "CONSTANCE72",
                            PasswordHash = "AQAAAAIAAYagAAAAEC91cfeETfzO878DQCHOxPy2I2Ui74SNABZauPRHC8ZKzNuOYDKrDX7KTanZl6Cv6g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3c2e84c7-408f-49b7-8327-be65f86e06f7",
                            TwoFactorEnabled = false,
                            UserName = "Fletcher9"
                        },
                        new
                        {
                            Id = "0fa1ef75-e675-49b3-b6e4-edca6ef451ca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5217299e-7f51-4c32-9467-217d75482525",
                            Email = "Jazmyne26@hotmail.com",
                            EmailConfirmed = false,
                            IsLibrarian = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "NATHAN.SCHAEFER20@HOTMAIL.COM",
                            NormalizedUserName = "MURIEL10",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ6kAZ1qchyig+UT6qhYa24nEPDPfCVX2J+WDZlMw65JVYOA264jVe+Tk70zpHBB1A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9826f6a8-f412-4ac4-b24f-ca4e812cc7d4",
                            TwoFactorEnabled = false,
                            UserName = "Floy.Leffler99"
                        },
                        new
                        {
                            Id = "36335a6c-5104-4aed-8d8e-278d91f6bd8b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d1ff317-6004-4f0e-8d35-062f815d851a",
                            Email = "Mohamed.Steuber43@gmail.com",
                            EmailConfirmed = false,
                            IsLibrarian = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TAMIA58@GMAIL.COM",
                            NormalizedUserName = "SYDNEE.YOST45",
                            PasswordHash = "AQAAAAIAAYagAAAAEC+sKmzZWm6jfyl0SNynkkPbqKHmIneFCetUbXfiwe2SA8fiVrTLxeFDKxmS7GyAhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "20c1a762-627c-4134-8198-5886c06986e1",
                            TwoFactorEnabled = false,
                            UserName = "Dillan_Lynch93"
                        },
                        new
                        {
                            Id = "50becd4a-bda0-406b-92d1-e1225dd8090e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "64d606d1-6485-4dcc-8d20-8abdfa05f142",
                            Email = "Rasheed_Marquardt@hotmail.com",
                            EmailConfirmed = false,
                            IsLibrarian = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "IMANI_DENESIK@GMAIL.COM",
                            NormalizedUserName = "DARRION.DIETRICH45",
                            PasswordHash = "AQAAAAIAAYagAAAAEFYcmx6q0g+4y71D4ahNi++ry7m87/WaQvfsIldxxSduZMFzmJsPbFt2gcM0xuM1uQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a3e867c-d395-49e6-847d-7c1414b0f752",
                            TwoFactorEnabled = false,
                            UserName = "Hermann.Gutmann40"
                        },
                        new
                        {
                            Id = "5abeb6ac-ef87-4bfa-b19f-52e43d373fb0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9243b059-f572-4c2e-b7c5-4f0b32f57e14",
                            Email = "Rosalee.Konopelski@gmail.com",
                            EmailConfirmed = false,
                            IsLibrarian = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BRADEN_CARROLL39@HOTMAIL.COM",
                            NormalizedUserName = "NATASHA17",
                            PasswordHash = "AQAAAAIAAYagAAAAEEiZJuP+WisDlrzpX5eQ5mrZp/QiIK9im+vhzp6DIqZCAwPVkL5wVYzPoOJs0zgUJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f068afe-9413-4f90-a716-7a3e06d5ec3f",
                            TwoFactorEnabled = false,
                            UserName = "Kennedi_Smitham"
                        },
                        new
                        {
                            Id = "a9444d29-60d5-456e-840d-25f5533fb2ca",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1174587b-0f51-41a8-971b-e1fc9b950f82",
                            Email = "Kaycee66@gmail.com",
                            EmailConfirmed = false,
                            IsLibrarian = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DANIELLE.CRONA38@HOTMAIL.COM",
                            NormalizedUserName = "ALENE_HARTMANN11",
                            PasswordHash = "AQAAAAIAAYagAAAAEPqMfmGphT3Q5AWNRs6WIVaOiaroHlYXmgsB1b/xGgKFQsjtU7jtPF15B7Nig4NLlw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "01d9b695-29a0-43be-a901-86d74af9413a",
                            TwoFactorEnabled = false,
                            UserName = "Lizzie.Rolfson"
                        },
                        new
                        {
                            Id = "d0aa8f2a-1b45-4eb5-a1cb-efe8236d91a0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d8c46728-4d53-4646-b558-9194afc3f9fd",
                            Email = "Leopold_Parisian@yahoo.com",
                            EmailConfirmed = false,
                            IsLibrarian = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KATHLEEN.GUSIKOWSKI@HOTMAIL.COM",
                            NormalizedUserName = "LOTTIE_KUTCH89",
                            PasswordHash = "AQAAAAIAAYagAAAAEKeYc3wzP22Bjuy5v518uvmfjk0RTmVXjxrdoS1hXTmhiZ4CLKNv4Uf083neJZQs9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "626e5dbe-1d8e-4474-922b-2c905af4946c",
                            TwoFactorEnabled = false,
                            UserName = "Elsa_Witting"
                        },
                        new
                        {
                            Id = "9fdfcc5b-8cf7-44d3-979e-0a99966ab7c1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31b8cfc7-9f74-473e-95de-434e3ebcbeee",
                            Email = "Georgiana_Cummerata66@yahoo.com",
                            EmailConfirmed = false,
                            IsLibrarian = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OMARI37@GMAIL.COM",
                            NormalizedUserName = "WILSON.TOY14",
                            PasswordHash = "AQAAAAIAAYagAAAAENuS8DQmkGZpDHvqoHX9XNPpIRmzxr1PsPSTjv/M2UsGYg8T8u6W+ntfqbvS1hpqXQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7feac5e9-a75c-4884-92b9-c004fdde5f23",
                            TwoFactorEnabled = false,
                            UserName = "Jaquan32"
                        },
                        new
                        {
                            Id = "2ed7fe43-3e5e-4124-9f78-357dd5a719da",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a6cf48d5-b28c-4dde-a3b7-0dcf3279b89d",
                            Email = "Eve47@gmail.com",
                            EmailConfirmed = false,
                            IsLibrarian = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LEMUEL_LIND@HOTMAIL.COM",
                            NormalizedUserName = "MILES_MOHR",
                            PasswordHash = "AQAAAAIAAYagAAAAENsETr27wEsreB4yo6MXYgZH6gwn/36V8lj+avDok48l+rJnuRLcz5hbf/gCfMy9iw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae723d3b-19bd-4d78-b652-078d648824ab",
                            TwoFactorEnabled = false,
                            UserName = "Karelle_Will17"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.HasOne("LibraryApp.Models.User", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LibraryApp.Models.Review", b =>
                {
                    b.HasOne("LibraryApp.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LibraryApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LibraryApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LibraryApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LibraryApp.Models.User", b =>
                {
                    b.Navigation("BorrowedBooks");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
